global:
  scrape_interval: 15s # 전체 스크랩 주기 (15초)

scrape_configs:
  - job_name: "prod-nestjs"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api.handybus.co.kr"]

  - job_name: "prod-node-exporter"
    static_configs:
      - targets: ["43.200.88.16:9100"]

  - job_name: "prod-mysql-exporter"
    static_configs:
      - targets: ["mysql_exporter_prod:9104"]

  - job_name: "dev-nestjs"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["dev.api.handybus.co.kr"]

  - job_name: "dev-node-exporter"
    static_configs:
      - targets: ["43.200.7.197:9100"]

  - job_name: "dev-mysql-exporter"
    static_configs:
      - targets: ["mysql_exporter_dev:9104"]
