global:
  scrape_interval: 15s # 전체 스크랩 주기 (15초)

scrape_configs:
  - job_name: "prod-nestjs"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["43.200.88.16:3000"]

  - job_name: "prod-node-exporter"
    static_configs:
      - targets: ["43.200.88.16:9100"]

  - job_name: "dev-nestjs"
    metrics_path: "/metrics" # NestJS 애플리케이션에서 매트릭을 노출하는 엔드포인트
    static_configs:
      - targets: ["43.200.7.197:3000"] # NestJS 서버의 IP와 포트 (필요에 따라 수정)

  - job_name: "dev-node-exporter"
    static_configs:
      - targets: ["43.200.7.197:9100"]
